name: Generate sim names

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate names
        run: |
          python scripts/generate_names.py

      - name: Commit generated files (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add BONDx/sim_names.json BONDx/sim_names.csv || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-generate sim names"
            git push
          else
            echo "No changes to commit."
          fi
