name: lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python version
        run: python3 --version
      - name: Check repo tree
        run: ls -R
