name: next-ui-build

on:
  pull_request:
  push:
    branches: [ main, master, feat/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui-next
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ui-next/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
